// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type Blocks = {
  /**
   * Content blocks
   */
  blocks?: Array<
    | {
        /**
         * Selected
         */
        _selected: "blocks-text";

        /**
         * Text
         */
        "blocks-text": import("..").BlocksText;
      }
    | {
        /**
         * Selected
         */
        _selected: "blocks-images";

        /**
         * Images
         */
        "blocks-images": import("..").BlocksImages;
      }
    | {
        /**
         * Selected
         */
        _selected: "blocks-text-highlighted";

        /**
         * Highlighted text
         */
        "blocks-text-highlighted": import("..").BlocksTextHighlighted;
      }
    | {
        /**
         * Selected
         */
        _selected: "blocks-accordion";

        /**
         * Accordion
         */
        "blocks-accordion": import("..").BlocksAccordion;
      }
    | {
        /**
         * Selected
         */
        _selected: "blocks-cards";

        /**
         * Cards
         */
        "blocks-cards": import("..")._BlocksColor & import("..").BlocksCards & import("..")._BlocksLinkToMore;
      }
    | {
        /**
         * Selected
         */
        _selected: "blocks-quote";

        /**
         * Quote
         */
        "blocks-quote": import("..").BlocksQuote;
      }
    | {
        /**
         * Selected
         */
        _selected: "blocks-map";

        /**
         * Map
         */
        "blocks-map": import("..").BlocksMap;
      }
    | {
        /**
         * Selected
         */
        _selected: "blocks-reuse";

        /**
         * Reuse
         */
        "blocks-reuse": import("..").BlocksReuse;
      }
  >;
};
