// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type _BlocksCard = import("./_blocks-card")._BlocksCard;
export type _BlocksColor = import("./_blocks-color")._BlocksColor;
export type _BlocksIntro = import("./_blocks-intro")._BlocksIntro;
export type _BlocksLinkToMore = import("./_blocks-link-to-more")._BlocksLinkToMore;
export type _BlocksTitle = import("./_blocks-title")._BlocksTitle;
export type Blocks = import("./blocks").Blocks;
export type BlocksAccordion = import("./blocks-accordion").BlocksAccordion;
export type BlocksCards = import("./blocks-cards").BlocksCards;
export type BlocksImages = import("./blocks-images").BlocksImages;
export type BlocksMap = import("./blocks-map").BlocksMap;
export type BlocksQuote = import("./blocks-quote").BlocksQuote;
export type BlocksReuse = import("./blocks-reuse").BlocksReuse;
export type BlocksText = import("./blocks-text").BlocksText;
export type BlocksTextHighlighted = import("./blocks-text-highlighted").BlocksTextHighlighted;
