// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type BlocksQuote = {
  /**
   * Quote
   */
  quote: string;

  /**
   * Quoted by
   */
  attribution?: string;

  /**
   * Image of the person quoted
   */
  imageId?: string;
};
