// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type BlocksImages = {
  /**
   * Image
   */
  items: Array<{
    /**
     * Image
     */
    imageId: string;

    /**
     * Description of the image (alt text)
     */
    altText: string;

    /**
     * Caption
     */
    caption?: string;
  }>;
};
