// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export type _BlocksLinkToMore = {
  /**
   * Link to content
   */
  linkToMoreContentId?: string;

  /**
   * Bottom link text
   */
  linkToMoreText?: string;
};
